@startuml

User -> (Перегляд бази даних)
(Перегляд бази даних) <|-right-(Перегляд таблиць)

User --> (Створення бази даних)
(Створення бази даних) <|-right- (Створення таблиць)

User ---> (Редагування бази даних)

User -left-> (Копіювання баз даних)

(Редагування бази даних) <|-up- (Створення таблиць)
(Редагування бази даних) <|-left- (Видалення таблиць)
(Редагування бази даних) <|-right- (Редагування таблиць)
(Редагування бази даних) <|-right- (Об'єднання таблиць)

(Редагування таблиць) <|-down- (Додавання рядка)
(Редагування таблиць) <|-down- (Додавання стовпчика)
(Редагування таблиць) <|-down- (Видалення стовпчика)
(Редагування таблиць) <|-down- (Видалення рядка)
(Редагування таблиць) <|-up- (Редагування рядка)
(Редагування таблиць) <|-right- (Редагування стовпчика)

@enduml